export const mockAPIData = {
  // employee_info: {
  //   emp_code: 'KYC10018',
  //   Fullname: 'Demo Gupta',
  //   designation: 'Software Development Engineer',
  //   department: 'Development Functions',
  //   work_location: 'NCR',
  //   period: ['Week #23(1/Jun/2025 - 7/Jun/2025', 'Week #27(17/Jun/2025 - 24/Jun/2025']
  // },
  roles_responsibility: [
    { Division: 'Development Functions', function_code: 'DEV-ARC-DEF', FunctionTitle: 'Define the architecture for the SaaS platform', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-ARC-SUP', FunctionTitle: 'Troubleshoot support issues related to architecture flaws', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-ARC-SCL', FunctionTitle: 'Improve architecture scalability and performance', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-BE-COD', FunctionTitle: 'Write and maintain backend code', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-BE-DBG', FunctionTitle: 'Debug backend issues and resolve errors', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-BE-DOC', FunctionTitle: 'Document backend workflows for future reference', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-FE-DES', FunctionTitle: 'Design and update front-end user interfaces', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-FE-BUG', FunctionTitle: 'Resolve front-end bugs and issues', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-FE-OPT', FunctionTitle: 'Optimize front-end for performance and load times', Perform: true, Manage: false, Audit: false, Define: false },
    { Division: 'Development Functions', function_code: 'DEV-CODE-CVS', FunctionTitle: 'Code version controls and repos management', Perform: true, Manage: false, Audit: false, Define: false },
  ],
  weekly_summary: [
    { week: '13–19 Apr', weekly_success: 'Updated UI components and modified reports.', work_days: 4, WFH: 2, WFO: 2, Efforts: 55, Leaves: 0, Holidays: 1, ED: 1, Roadblocks: '–', unfinishedTasks: '–', nextActions: 'Flexible learning time during work hours for exploring new tools or tech stacks would boost confidence and skills.', remarks: 'Submitted' },
    { week: '20–26 Apr', weekly_success: 'Created control test files and extended database integration.', work_days: 5, WFH: 3, WFO: 1, Efforts: 53, Leaves: 1, Holidays: 0, ED: 1, Roadblocks: '–', unfinishedTasks: '–', nextActions: '–', remarks: 'Submitted' },
    { week: '27 Apr – 3 May', weekly_success: 'Deployed code on dev server using IP-based access, analyzed AM reports, and initiated Live PEP certification test.', work_days: 4, WFH: 3, WFO: 1, Efforts: 42.5, Leaves: 0, Holidays: 1, ED: 0, Roadblocks: '–', unfinishedTasks: '–', nextActions: 'Reviewed.', remarks: 'Submitted' },
    { week: '4–10 May', weekly_success: 'Completed Live PEP certification test, resolved SDN test strategy bugs, and worked on Account Preference API.', work_days: 5, WFH: 4, WFO: 1, Efforts: 53, Leaves: 0, Holidays: 0, ED: 0, Roadblocks: '–', unfinishedTasks: '–', nextActions: 'Reviewed.', remarks: 'Submitted' },
  ],
  weekly_stats: {
    Officialworkingdays: 32,
    LeavesTaken: 1,
    TotalHoursWorked: 371.5,
  },
  goals_data: [
    {
      division: "Development Functions",
      code: "G001",
      title: "Feature Delivery",
      desc: "Ensure timely and efficient delivery of customer-committed features (Deliver committed features to production as per sprint/release plans)",
      target: "≥ 90%",
      uom: "%",
      period: "Monthly",
      dataCollection: "Sprint/Release Tracker / JIRA/ Azure DevOps",
      red: "< 80%",
      orange: "80–89%",
    },
    {
      division: "Development Functions",
      code: "G002",
      title: "Code Quality",
      desc: "Ensure high-quality, maintainable, and low-defect codebase\nMaintain minimum 80% code quality score across codebase (e.g., via SonarQube)",
      target: "≥ 80%",
      uom: "%",
      period: "Monthly",
      dataCollection:
        "Static Code Analysis / SonarQube Reports / specific toolchain (e.g., GitHub, Azure DevOps, Jenkins)?",
      red: "< 70%",
      orange: "< 80%",
    },
    {
      division: "Development Functions",
      code: "G003",
      title: "Code Security",
      desc: "Ensure code adheres to secure development standards to minimize vulnerabilities (All code must comply with secure coding guidelines and pass security scans before deployment)",
      target: "1",
      uom: "%",
      period: "Monthly",
      dataCollection: "Static Security Scans / SAST/DAST Reports",
      red: "< 90%",
      orange: "90–99%",
    },
    {
      division: "Development Functions",
      code: "G004",
      title: "Bug Reduction",
      desc: "Minimize bugs identified during QA and post-release through better dev practices (Reduce number of bugs detected during QA and after release by improving code and test quality)",
      target: "≤ 5/sprint",
      uom: "Count",
      period: "Monthly",
      dataCollection: "Bug Tracking System / JIRA / Bugzilla, etc",
      red: "> 10",
      orange: "6–10",
    },
    {
      division: "Development Functions",
      code: "G005",
      title: "Code Review Efficiency",
      desc: "Ensure timely completion of code reviews to maintain delivery velocity (Complete code reviews within 24 hours of PR creation)",
      target: "≤ 24",
      uom: "Hours",
      period: "Monthly",
      dataCollection: "Git, Bitbucket, GitHub PRs [PR Analytics Tools]",
      red: "> 48 hrs",
      orange: "25–48 hrs",
    },
    {
      division: "Development Functions",
      code: "G006",
      title: "Commit Regularity",
      desc: "Ensure consistent code commits to support continuous integration and visibility",
      target: "≥ 1 commit/day/dev",
      uom: "Count",
      period: "Monthly",
      dataCollection: "Git Logs / Dev Tools",
      red: "< 0.5/day/dev",
      orange: "0.5–0.9/day/dev",
    },
    {
      division: "Development Functions",
      code: "G007",
      title: "CI/CD Reliability",
      desc: "Ensure consistent success of CI/CD pipeline to support stable releases (Maintain a high success rate of automated build and deployment jobs across environments)",
      target: "≥ 95%",
      uom: "%",
      period: "Monthly",
      dataCollection: "CI/CD Logs (Jenkins, GitHub Actions, etc.)",
      red: "< 85%",
      orange: "85–94%",
    },
    {
      division: "Development Functions",
      code: "G008",
      title: "Tech Debt Reduction",
      desc: "Manage and reduce technical debt through planned refactoring and backlog cleanup (Complete 80% of planned refactoring tasks and backlog tech debt items each quarter)",
      target: "≥ 80%",
      uom: "%",
      period: "Monthly",
      dataCollection:
        "Jira, SonarQube, Git Logs, Issue Tracker, Static Code Tools",
      red: "< 60%",
      orange: "60–79%",
    },
    {
      division: "Development Functions",
      code: "G009",
      title: "API Responsiveness",
      desc: "Ensure optimal performance of backend API endpoints for user experience (Maintain 95% of API requests meeting defined performance SLAs (e.g., < 500ms))",
      target: "≥ 95% within SLA",
      uom: "%",
      period: "Monthly",
      dataCollection:
        "APM Tools (e.g., New Relic, Datadog), API Gateway Logs",
      red: "< 90%",
      orange: "90–94%",
    },
    {
      division: "Development Functions",
      code: "G010",
      title: "Unit Test Coverage",
      desc: "Ensure sufficient unit test coverage across the codebase to catch bugs early (Maintain at least 85% unit test coverage on all critical components)",
      target: "≥ 85%",
      uom: "%",
      period: "Monthly",
      dataCollection:
        "Code Coverage Reports (Coverage Tools (e.g., Jacoco, Istanbul)",
      red: "< 70%",
      orange: "70–84%",
    },
    {
      division: "Development Functions",
      code: "G011",
      title: "Agile Ceremony Engagement",
      desc: "Ensure active participation of all relevant team members in sprint planning and related Agile ceremonies (Achieve at least 95% attendance and active involvement during sprint planning meetings)",
      target: "≥ 95%",
      uom: "%",
      period: "Sprint",
      dataCollection:
        "Meeting Attendance Logs (Agile Tools (Jira, Confluence, Zoom logs)",
      red: "< 80%",
      orange: "80–94%",
    },
  ],
};

// export const mockUsers = [
//   { username: 'Stark', password: 'password123', name: 'Robert Stark', emp_code: 'KYC10018' },
//   { username: 'john', password: 'doe123', name: 'John Doe', emp_code: 'KYC10019' },
// ];

// export function mockLogin(username: string, password: string) {
//   return new Promise<{ success: boolean; user?: any; message?: string }>((resolve) => {
//     setTimeout(() => {
//       const user = mockUsers.find(
//         (u) => u.username === username && u.password === password
//       );
//       if (user) {
//         resolve({ success: true, user });
//       } else {
//         resolve({ success: false, message: 'Invalid username or password' });
//       }
//     }, 500); // simulate network delay
//   });
// }

export const weekly_goals = [
  {
    "goal_id": "DEVFUN-001          ",
    "goal_title": "Feature Delivery",
    "goal_description": "Ensure timely and efficient delivery of customer-committed features (Deliver committed features to production as per sprint/release plans)",
    "goal_target": "= 90%",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Delivered Search Preference API (Exclusion Words).\n- Integrated in CIQ.\n- Worked on UI and backend for Live Adverse Media Certification Test (3PO OFF/ON).",
    "effort": 24,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "Handling dynamic preference states for 3PO ON/OFF.",
    "unfinished_tasks": "Integration of adverse media API for toggling 3PO ON/OFF + file download logic."
  },
  {
    "goal_id": "DEVFUN-001          ",
    "goal_title": "Feature Delivery",
    "goal_description": "Ensure timely and efficient delivery of customer-committed features (Deliver committed features to production as per sprint/release plans)",
    "goal_target": "= 90%",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Completed 3PO ON/OFF preference API integration.\r\n- Finalized and deployed AM (Adverse Media) test strategies.\r\n- Filled Performance Review Sheet.",
    "effort": 20,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "Redownload for 3PO-ON pending due to credit exhaustion.",
    "unfinished_tasks": "Retest redownload logic once OpenAI access is restored."
  },
  {
    "goal_id": "DEVFUN-001          ",
    "goal_title": "Feature Delivery",
    "goal_description": "Ensure timely and efficient delivery of customer-committed features (Deliver committed features to production as per sprint/release plans)",
    "goal_target": "= 90%",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Added AM rules/preferences on Account Config page.\r\n- Completed CIQ email report attachment.\r\n- Enabled custom upload for all test cases\r\n.- SDN Live real-time filters enabled.\r\n- Post-deployment testing of all features.",
    "effort": 19,
    "status": "Completed",
    "own_rating": "",
    "challenges": "SDN test had off-by-one error in record count.\r\nProxy issue in large test file upload.",
    "unfinished_tasks": "Ongoing improvements on SDN Test strategy logic."
  },
  {
    "goal_id": "DEVFUN-001          ",
    "goal_title": "Feature Delivery",
    "goal_description": "Ensure timely and efficient delivery of customer-committed features (Deliver committed features to production as per sprint/release plans)",
    "goal_target": "= 90%",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Completed account-level configurability for record limit and file size.\r\n- Displayed test strategy as per account privilege.\r\n- Displayed only non-empty fields in preference config mapping JSON.\r\n- Worked on preference description + example presentation.\r\n- Added input file description in custom upload section.\r\n- Deployed changes to production and tested.\r\n- Added test validation for strategy visibility per account privilege.",
    "effort": 22,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "Access-based strategy visibility needed UI logic refinement.",
    "unfinished_tasks": "Custom report enhancement for specialized display still in progress."
  },
  {
    "goal_id": "DEVFUN-002          ",
    "goal_title": "Code Quality",
    "goal_description": "Ensure high-quality, maintainable, and low-defect codebase (Maintain minimum 80% code quality score across codebase e.g., via SonarQube)",
    "goal_target": "= 80%",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Followed secure and standard practices in backend development (Spring Boot mail handler, Search Pref API).",
    "effort": 4,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "Minor logic changes needed after code review (Shankar’s feedback).",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-002          ",
    "goal_title": "Code Quality",
    "goal_description": "Ensure high-quality, maintainable, and low-defect codebase (Maintain minimum 80% code quality score across codebase e.g., via SonarQube)",
    "goal_target": "= 80%",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Refactored AM 3PO-ON retry \u0026 redownload logic after initial testing.\r\n- Implemented modular email integration.",
    "effort": 4,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-002          ",
    "goal_title": "Code Quality",
    "goal_description": "Ensure high-quality, maintainable, and low-defect codebase (Maintain minimum 80% code quality score across codebase e.g., via SonarQube)",
    "goal_target": "= 80%",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Refined UI messages and input fields.\r\n- Refactored AM Report summary logic.\r\n- Cleaned up About This Page and Account Config UI.\r\n- Updated Generate Name Variant prompts for clarity.",
    "effort": 5,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Continuous UI improvements driven by team feedback.",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-002          ",
    "goal_title": "Code Quality",
    "goal_description": "Ensure high-quality, maintainable, and low-defect codebase (Maintain minimum 80% code quality score across codebase e.g., via SonarQube)",
    "goal_target": "= 80%",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Modularized custom report logic for sub-component rendering.\r\n- Improved clarity in preference example and description.\r\n- Added strong alert/message in live variant generation flow.",
    "effort": 6,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "Keeping alert messaging consistent across pages.",
    "unfinished_tasks": "Final review of report modular components."
  },
  {
    "goal_id": "DEVFUN-003          ",
    "goal_title": "Code Security",
    "goal_description": "Ensure code adheres to secure development standards to minimize vulnerabilities (All code must comply with secure coding guidelines and pass security scans before deployment)",
    "goal_target": "100%",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Ensured secured endpoints in new Search Preference APIs.\r\n- Used validation for file handling and exclusions.",
    "effort": 2,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-003          ",
    "goal_title": "Code Security",
    "goal_description": "Ensure code adheres to secure development standards to minimize vulnerabilities (All code must comply with secure coding guidelines and pass security scans before deployment)",
    "goal_target": "100%",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-003          ",
    "goal_title": "Code Security",
    "goal_description": "Ensure code adheres to secure development standards to minimize vulnerabilities (All code must comply with secure coding guidelines and pass security scans before deployment)",
    "goal_target": "100%",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-003          ",
    "goal_title": "Code Security",
    "goal_description": "Ensure code adheres to secure development standards to minimize vulnerabilities (All code must comply with secure coding guidelines and pass security scans before deployment)",
    "goal_target": "100%",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-004          ",
    "goal_title": "Bug Reduction",
    "goal_description": "Minimize bugs identified during QA and post-release through better dev practices (Reduce number of bugs detected during QA and after release by improving code and test quality)",
    "goal_target": "= 5/sprint",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Investigated \u0026 fixed issue with batch service on dev account.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Batch service failing unexpectedly in dev environment.",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-004          ",
    "goal_title": "Bug Reduction",
    "goal_description": "Minimize bugs identified during QA and post-release through better dev practices (Reduce number of bugs detected during QA and after release by improving code and test quality)",
    "goal_target": "= 5/sprint",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Deployed fixes for production bugs from previous release.\r\n- Investigated unreproducible issue in dev but found root cause in prod.",
    "effort": 3.5,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Bugs that were not replicable in local/dev environments.",
    "unfinished_tasks": "None"
  },
  {
    "goal_id": "DEVFUN-004          ",
    "goal_title": "Bug Reduction",
    "goal_description": "Minimize bugs identified during QA and post-release through better dev practices (Reduce number of bugs detected during QA and after release by improving code and test quality)",
    "goal_target": "= 5/sprint",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Fixed off-by-one issue in SDN Live test.\r\n- Resolved proxy issue during large batch upload.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Large file submission caused proxy errors.",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-004          ",
    "goal_title": "Bug Reduction",
    "goal_description": "Minimize bugs identified during QA and post-release through better dev practices (Reduce number of bugs detected during QA and after release by improving code and test quality)",
    "goal_target": "= 5/sprint",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Resolved 2 report bugs raised by Ishaan.\r\n- Fixed date filter misalignment.\r\n- Fixed save button text issue.",
    "effort": 3.5,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Minor UI regressions after new updates.",
    "unfinished_tasks": "Monitor UI closely for further visual issues."
  },
  {
    "goal_id": "DEVFUN-005          ",
    "goal_title": "Code Review Efficiency",
    "goal_description": "Ensure timely completion of code reviews to maintain delivery velocity (Complete code reviews within 24 hours of PR creation)",
    "goal_target": "= 24",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Incorporated review feedback from Shankar for Preference API implementation.",
    "effort": 2,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "Minor pending UI-level changes."
  },
  {
    "goal_id": "DEVFUN-005          ",
    "goal_title": "Code Review Efficiency",
    "goal_description": "Ensure timely completion of code reviews to maintain delivery velocity (Complete code reviews within 24 hours of PR creation)",
    "goal_target": "= 24",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Reviewed changes for retry, redownload logic and production fixes.",
    "effort": 2,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-005          ",
    "goal_title": "Code Review Efficiency",
    "goal_description": "Ensure timely completion of code reviews to maintain delivery velocity (Complete code reviews within 24 hours of PR creation)",
    "goal_target": "= 24",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Reviewed AM Report changes and incorporated feedback from Apu.\r\n- Code-reviewed SDN Live \u0026 Account Config changes before deployment.",
    "effort": 2,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-005          ",
    "goal_title": "Code Review Efficiency",
    "goal_description": "Ensure timely completion of code reviews to maintain delivery velocity (Complete code reviews within 24 hours of PR creation)",
    "goal_target": "= 24",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Got preference description changes reviewed before deployment.\r\n- Participated in review of custom upload enhancements.",
    "effort": 2,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-006          ",
    "goal_title": "Commit Regularity",
    "goal_description": "Ensure consistent code commits to support continuous integration and visibility",
    "goal_target": "= 1 commit/day/dev",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Regular commits while building and integrating Search Preference APIs and UI strategies.",
    "effort": 1,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-006          ",
    "goal_title": "Commit Regularity",
    "goal_description": "Ensure consistent code commits to support continuous integration and visibility",
    "goal_target": "= 1 commit/day/dev",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Regular commits across AM strategy work, retry logic, and prod fix deployments.",
    "effort": 1,
    "status": "Completed",
    "own_rating": "",
    "challenges": "None",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-006          ",
    "goal_title": "Commit Regularity",
    "goal_description": "Ensure consistent code commits to support continuous integration and visibility",
    "goal_target": "= 1 commit/day/dev",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Regular daily manual commits across SDN, AM, UI, and test deployment workstreams.",
    "effort": 1,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-006          ",
    "goal_title": "Commit Regularity",
    "goal_description": "Ensure consistent code commits to support continuous integration and visibility",
    "goal_target": "= 1 commit/day/dev",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Regular commits for preference config, report logic, and privilege-based display updates.",
    "effort": 1,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-007          ",
    "goal_title": "CI/CD Reliability",
    "goal_description": "Ensure consistent success of CI/CD pipeline to support stable releases (Maintain a high success rate of automated build and deployment jobs)",
    "goal_target": "= 95%",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-007          ",
    "goal_title": "CI/CD Reliability",
    "goal_description": "Ensure consistent success of CI/CD pipeline to support stable releases (Maintain a high success rate of automated build and deployment jobs)",
    "goal_target": "= 95%",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Successfully deployed new strategy changes to production manually.\r\n- Fixed production-only issues post-deployment.",
    "effort": 4,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Deployment-specific bugs surfacing only in prod.",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-007          ",
    "goal_title": "CI/CD Reliability",
    "goal_description": "Ensure consistent success of CI/CD pipeline to support stable releases (Maintain a high success rate of automated build and deployment jobs)",
    "goal_target": "= 95%",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Deployed all weekly changes (SDN, AM, Account Config UI) to production.\r\n- Verified post-deployment functionality.",
    "effort": 4,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Proxy error challenge resolved before deploy.\r\nAM Report changes required validation.",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-007          ",
    "goal_title": "CI/CD Reliability",
    "goal_description": "Ensure consistent success of CI/CD pipeline to support stable releases (Maintain a high success rate of automated build and deployment jobs)",
    "goal_target": "= 95%",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Successfully deployed changes to production on 27.06.25, manually.\r\n- Performed complete testing post-deployment.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-008          ",
    "goal_title": "Tech Debt Reduction",
    "goal_description": "Manage and reduce technical debt through planned refactoring and backlog cleanup (Complete 80% of planned refactoring and tech debt items)",
    "goal_target": "= 80%",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Refactored mail handler logic to support future extensibility.\r\n- Modularized preference API for easier scaling.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-008          ",
    "goal_title": "Tech Debt Reduction",
    "goal_description": "Manage and reduce technical debt through planned refactoring and backlog cleanup (Complete 80% of planned refactoring and tech debt items)",
    "goal_target": "= 80%",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-008          ",
    "goal_title": "Tech Debt Reduction",
    "goal_description": "Manage and reduce technical debt through planned refactoring and backlog cleanup (Complete 80% of planned refactoring and tech debt items)",
    "goal_target": "= 80%",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Modified About This Page section UI and refactored Account Config layout.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Minor layout mismatches across environments.",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-008          ",
    "goal_title": "Tech Debt Reduction",
    "goal_description": "Manage and reduce technical debt through planned refactoring and backlog cleanup (Complete 80% of planned refactoring and tech debt items)",
    "goal_target": "= 80%",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Modularized report component rendering for better maintainability.\r\n- Streamlined preference config structure (non-empty fields).",
    "effort": 6,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "Older report structure was not adaptable to custom use cases.",
    "unfinished_tasks": "Modularize remaining legacy report components."
  },
  {
    "goal_id": "DEVFUN-009          ",
    "goal_title": "API Responsiveness",
    "goal_description": "Ensure optimal performance of backend API endpoints for user experience (Maintain 95% of API requests within SLA, e.g., \u003c 500ms)",
    "goal_target": "= 95% within SLA",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Built and validated Search Preference API with acceptable response time.\r\n- Avoided heavy payloads while reading CSVs.",
    "effort": 2,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "CSV merging could be slow when dataset increases.",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-009          ",
    "goal_title": "API Responsiveness",
    "goal_description": "Ensure optimal performance of backend API endpoints for user experience (Maintain 95% of API requests within SLA, e.g., \u003c 500ms)",
    "goal_target": "= 95% within SLA",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Verified performance of email sender and AM APIs post-deployment.",
    "effort": 2,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "Performance verification delayed due to blocked OpenAI calls.",
    "unfinished_tasks": "Reverify with OpenAI re-enabled."
  },
  {
    "goal_id": "DEVFUN-009          ",
    "goal_title": "API Responsiveness",
    "goal_description": "Ensure optimal performance of backend API endpoints for user experience (Maintain 95% of API requests within SLA, e.g., \u003c 500ms)",
    "goal_target": "= 95% within SLA",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Investigated and resolved proxy issue due to large file submission to backend.-\r\n Improved file handling logic in batch submission.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "Backend timeout when large files submitted.",
    "unfinished_tasks": "Revalidate with larger batch cases post-deploy."
  },
  {
    "goal_id": "DEVFUN-009          ",
    "goal_title": "API Responsiveness",
    "goal_description": "Ensure optimal performance of backend API endpoints for user experience (Maintain 95% of API requests within SLA, e.g., \u003c 500ms)",
    "goal_target": "= 95% within SLA",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Improved speed of Live Variant Generation.\r\n- Added alert message to reduce backend overuse.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-010          ",
    "goal_title": "Unit Test Coverage",
    "goal_description": "Ensure sufficient unit test coverage across the codebase (Maintain at least 85% unit test coverage on all critical components)",
    "goal_target": "= 85%",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-010          ",
    "goal_title": "Unit Test Coverage",
    "goal_description": "Ensure sufficient unit test coverage across the codebase (Maintain at least 85% unit test coverage on all critical components)",
    "goal_target": "= 85%",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-010          ",
    "goal_title": "Unit Test Coverage",
    "goal_description": "Ensure sufficient unit test coverage across the codebase (Maintain at least 85% unit test coverage on all critical components)",
    "goal_target": "= 85%",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-010          ",
    "goal_title": "Unit Test Coverage",
    "goal_description": "Ensure sufficient unit test coverage across the codebase (Maintain at least 85% unit test coverage on all critical components)",
    "goal_target": "= 85%",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-011          ",
    "goal_title": "Agile Ceremony Engagement",
    "goal_description": "Ensure active participation in sprint planning and Agile ceremonies (Achieve = 95% attendance and active involvement)",
    "goal_target": "= 95%",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Discussed test strategies with team.\r\n- Participated in prompt design for AI-based test generation.",
    "effort": 2,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-011          ",
    "goal_title": "Agile Ceremony Engagement",
    "goal_description": "Ensure active participation in sprint planning and Agile ceremonies (Achieve = 95% attendance and active involvement)",
    "goal_target": "= 95%",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Active discussion and review of AM 3PO flow with team\r\n-Planning for next test flow.",
    "effort": 2,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-011          ",
    "goal_title": "Agile Ceremony Engagement",
    "goal_description": "Ensure active participation in sprint planning and Agile ceremonies (Achieve = 95% attendance and active involvement)",
    "goal_target": "= 95%",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "- Took feedback during AM report review.\r\n- Coordinated UAT reviews.\r\n- Participated in production release discussions.",
    "effort": 3,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-011          ",
    "goal_title": "Agile Ceremony Engagement",
    "goal_description": "Ensure active participation in sprint planning and Agile ceremonies (Achieve = 95% attendance and active involvement)",
    "goal_target": "= 95%",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "- Engaged with UAT (Ishaan) to resolve bugs and improve usability.\r\n- Collaborated with team on report modularization and privilege access handling.",
    "effort": 2,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-099          ",
    "goal_title": "Ad-hoc Development Requests",
    "goal_description": "Monitor non-scheduled development activities including bug fixes, quick scripts, and hotfixes.",
    "goal_target": "\u003c=7",
    "week_start_date": "2025-05-25T00:00:00Z",
    "week_end_date": "2025-05-31T00:00:00Z",
    "action_performed": "- Created mail handler (Spring Boot backend) for future use.\r\n- Research on prompt creation for OpenAI test generation.",
    "effort": 3,
    "status": "In Progress",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "Integration of mail handler into frontend."
  },
  {
    "goal_id": "DEVFUN-099          ",
    "goal_title": "Ad-hoc Development Requests",
    "goal_description": "Monitor non-scheduled development activities including bug fixes, quick scripts, and hotfixes.",
    "goal_target": "\u003c=7",
    "week_start_date": "2025-06-08T00:00:00Z",
    "week_end_date": "2025-06-14T00:00:00Z",
    "action_performed": "- Integrated email sender logic into CIQ.\r\n- Filled out internal performance review sheet.",
    "effort": 7,
    "status": "Completed",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-099          ",
    "goal_title": "Ad-hoc Development Requests",
    "goal_description": "Monitor non-scheduled development activities including bug fixes, quick scripts, and hotfixes.",
    "goal_target": "\u003c=7",
    "week_start_date": "2025-06-15T00:00:00Z",
    "week_end_date": "2025-06-21T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  },
  {
    "goal_id": "DEVFUN-099          ",
    "goal_title": "Ad-hoc Development Requests",
    "goal_description": "Monitor non-scheduled development activities including bug fixes, quick scripts, and hotfixes.",
    "goal_target": "\u003c=7",
    "week_start_date": "2025-06-22T00:00:00Z",
    "week_end_date": "2025-06-28T00:00:00Z",
    "action_performed": "N/A",
    "effort": 0,
    "status": "N/A",
    "own_rating": "",
    "challenges": "N/A",
    "unfinished_tasks": "N/A"
  }
];

